### ISSUE TITLE
What does $SDK_ROOT mean

### ISSUE THREAD

**Issue by flipper44** [jumpinjackie/gdal4fdo#2]
You say to download to What does $SDK_ROOT I don't understand what is meant by this

**Comment by flipper44** [comment]
I created a folder Called $SDK_ROOT. 
Extracted release-1700-x64-dev.zip (msvc 2012) into that folder.
Overwrote makefile and Build from your zip file.
I'm confused by step 3: svn export Thirdparty\gdal from your FDO 3.9 or FDO 4.0 working copy to $SDK_ROOT\gdal So this is probably where I am going downhill.
I installed gdal-111-1700-x64-core.msi installer for the GDAL core components
then gdal-111-1700-x64-ecw-33.msi and gdal-111-1700-x64-mrsid.msi
I thin Copied the GDAL folder contents from C:\Program Files into $SDK_ROOT\gdal
I ran the VS 2012 Command line cd to SDK_Root and ran build.bat 64.
My Folder Structure is Similar to the downloadable version you made, however the gdalplugins folder is absolutely empty.

Did I get step 3 wrong or is there Something I need to edit in the BAT or makefile?

**Comment by jumpinjackie** [comment]
I use $VARIABLE_NAME convention in most of my README.md files that describe placeholders to variables/paths that you should fill in yourself.

So whatever path you have decided to use for $SDK_ROOT, replace all instances of $SDK_ROOT with your chosen path
